# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

msboot <- function(nrep, x, Wsel, stdz, ncore) {
    .Call('_EFBA_msboot', PACKAGE = 'EFBA', nrep, x, Wsel, stdz, ncore)
}

tsbootH0 <- function(x, rndraws, ncore) {
    .Call('_EFBA_tsbootH0', PACKAGE = 'EFBA', x, rndraws, ncore)
}

fhat <- function(X, N, stdz) {
    .Call('_EFBA_fhat', PACKAGE = 'EFBA', X, N, stdz)
}

ghat <- function(fhat) {
    .Call('_EFBA_ghat', PACKAGE = 'EFBA', fhat)
}

